### ISSUE TITLE
Vignette for treemix is incomplete

### ISSUE THREAD

**Issue by oviscanadensis** [marcomilanesi/BITE#2]
Hello,

I would like to use BITE to use treemix.  However, the section of the vignette describing treemix appears to not be completed yet.  Do you have a version of the vignette that is complete?

Thanks!

**Comment by marcomilanesi** [comment]
Dear Elizabeth, 
first of all thank you to use BITE. 
I'm sorry but we didn't complete the vignette yet. We are working on BITE v2. However, you can find some information how to use _treemix_ functions in the R help page. Do you have some specific doubt/problem? If you need more information/support, please don't hesitate to contact me at marco.milanesi.mm@gmail.com. 

Best regards!
