### ISSUE TITLE
Question about --bootstrap flag

### ISSUE THREAD

**Issue by ab08028** [marcomilanesi/BITE#3]
Hi there,
thanks for such a useful set of tools! I have a question about the treemix bootstrapping. I generated the scripts using treemix.scripts(), but noticed that in the script Treemix_bootstrap.sh the -bootstrap flag isn't given to treemix when running the bootstrap replicates. Without this flag, isn't the script just running replicates with different seeds, rather than true bootstraps that have resampled the data? 

The relevant code: 
	dowork() { 
		a=$RANDOM
		b=1\`date +%N\`
		let "c=$a+$b"
		treemix -i $2 -k $3 -se -m $4 -seed $c -o "bootstrap/"$5"_treemix_bootrep_"$1
	}

Shouldn't this be where the -bootstrap treemix flag is added to resample the data over your k-sized blocks? I have modified the code to be:
	dowork() { 
		a=$RANDOM
		b=1\`date +%N\`
		let "c=$a+$b"
		treemix **-bootstrap** -i $2 -k $3 -se -m $4 -seed $c -o "bootstrap/"$5"_treemix_bootrep_"$1
	}

Does this make sense? Thanks so much for your help!

Best,
Annabel

**Comment by marcomilanesi** [comment]
Dear Annabel, 
Thank you to find BITE useful and for your very helpful comment!

Of course the option “–bootstrap” need to be included in the code. Probably, during the code revision process, this part was accidentally removed. 

The BASH script was corrected and the package was updated. 

Thank you again for the help! For any further questions, please, don’t hesitate to contact me. 

Best!

Marco
