### ISSUE TITLE
Error message when running "Treemix_bootstrap.sh" bash ...54: export: Illegal option -f

### ISSUE THREAD

**Issue by SuanyQuesada** [marcomilanesi/BITE#4]
I am just starting to use treemix and I want to use BITE, but when I run the bash script "Treemix_bootstrap.sh" I got the error "54: export: Illegal option -f" . If I delete that line in the bash, I got emplty files... What can I do??  Thank you so much!

The line command was= 
sh ./BITE-master/BITE_1.2.0007/BITE/inst/scripts/treemix_scripts/Treemix_bootstrap.sh populations2.treemix.gz 3 6 500 NoOutgroup 10 ./ pru

**** RUNNING TREEMIX ****
./BITE-master/BITE_1.2.0007/BITE/inst/scripts/treemix_scripts/Treemix_bootstrap.sh: 54: export: Illegal option -f

Have a nice day!

**Comment by marcomilanesi** [comment]
Dear, 
thank you to use BITE! 
Which operating system are you using to run Treemix_bootstrap.sh script?

**Comment by SuanyQuesada** [comment]
Hi! I am using ubuntu 18.04

**Comment by marcomilanesi** [comment]
Another question, which is the version of export function and bash?

**Comment by SuanyQuesada** [comment]
The header of the bash script is this: #License: GPLv3 or later #Modification date: 2017-05-10 . And the name of the folder is BITE_1.2.0007
Thank you!

**Comment by marcomilanesi** [comment]
Thank you for your answer. However I'm interested to know the version of the export command installed in your Ubuntu machine.

**Comment by SuanyQuesada** [comment]
Hi, the version of the export command in my pc is: "GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)"
Thank you!

**Comment by marcomilanesi** [comment]
Thank you for your answer. 
Please try to run the "Treemix_bootstrap.sh" script using bash instead sh.

**Comment by SuanyQuesada** [comment]
Hi, Thank you for your answer. 
I ran the "Treemiz_bootstrap.sh" using bash and this ran, but now the script does not make all the gzip files of the bootstrap directory. I do not what is my new mistake..... Thank you in advice ! Have a nice day!

The command line was:
bash BITE-master/BITE_1.2.0007/BITE/inst/scripts/treemix_scripts/Treemix_bootstrap.sh populations2.treemix.gz 3 6 500 NoOutgroup 10 /home/suany/Downloads/phylip-3.697/exe/consense pru

The error message was: 

**** RUNNING TREEMIX ****
**** RUNNING TREEMIX: DONE ****
gzip: bootstrap/pru_treemix_bootrep_1.treeout.gz: No such file or directory
gzip: bootstrap/pru_treemix_bootrep_2.treeout.gz: No such file or directory
gzip: bootstrap/pru_treemix_bootrep_3.treeout.gz: No such file or directory
gzip: bootstrap/pru_treemix_bootrep_4.treeout.gz: No such file or directory
gzip: bootstrap/pru_treemix_bootrep_5.treeout.gz: No such file or directory
gzip: bootstrap/pru_treemix_bootrep_6.treeout.gz: No such file or directory
gzip: bootstrap/pru_treemix_bootrep_7.treeout.gz: No such file or directory
gzip: bootstrap/pru_treemix_bootrep_8.treeout.gz: No such file or directory
gzip: bootstrap/pru_treemix_bootrep_9.treeout.gz: No such file or directory
gzip: bootstrap/pru_treemix_bootrep_10.treeout.gz: No such file or directory
   ***** Boostrap procedure: DONE *****
   ***** Phylip - consensus tree construction: START *****
   ***** Phylip - consensus tree construction: DONE *****
**** RUNNING TREEMIX with Consensus tree ****
ERROR: Input Newick string with 1 populations. Input file has 9
**** RUNNING TREEMIX: DONE ****
TreeMix - Bootstrap Analysis --> DONE

**Comment by marcomilanesi** [comment]
Dear Suany, 
it seems that the script is not able to do the bootstrap procedure. I know that others run the script with BASH and, apparently, they did not have problems. 
The bootstrap folder was created?
I suggest to download and install the last version of the R package. After that, use the treemix.script function in R to save the Treemix_bootstrap.sh in your working directory. After that, run Treemix_bootstrap.sh again. 
I hope this will solve your problem
