### ISSUE TITLE
ADMIXTURE for multiple K values in a circle

### ISSUE THREAD

**Issue by josephresearcher** [marcomilanesi/BITE#6]
Hello
Please give an example to run
plots for ADMIXTURE for multiple K values in a circle 
Thanks

**Comment by capemaster** [comment]
Dear Joseph,
there is an help for each function.
Anyway, in case you missed it, the following code can be applied.

```
membercoeff.circos(in.file = "FilenameWithNoExtension",
                   maxK = 21,
                   K.to.plot = c(2:21),
                   pop.order.file = "poporder",
                   id.order.file = "idorder")

```
Flags are self explanatory. K numbers depend on your analysis.
Hope this helps.
