### ISSUE TITLE
membercoeff.circos() - error 

### ISSUE THREAD

**Issue by valentinatsarts** [marcomilanesi/BITE#7]
Hello!

Could you please give any advice on the following error while using membercoeff.circos function:

"Error in the.start:the.end : NA/NaN argument"

I am using the following code which is working for this function while using a similar dataset with another LD-prun threshold:

membercoeff.circos(in.file = "pruned_0.3",
                                 out.file = "test", maxK = 5,
                                 pop.order.file = "123.txt",
                                 software = "Admixture",
                                 K.to.plot = c(2,4))

I've compared the new files wit the previous ones, they do not seem to have any structural difference. I could attach the genotype files and respective Q estimates if necessary.

Many thanks!

Valentina

**Comment by capemaster** [comment]
Dear Valentina,
thank you for using the package.
My guess is that the population order file is malformed. Maybe you inserted a line at the eof?
Stefano

**Comment by valentinatsarts** [comment]
Dear Stefano,
thank you for your answer, I figured out the error related to individual ID coding, the pop order file was ok. 
Valentina

**Comment by capemaster** [comment]
Ok, thank you for the update.
I will close the discussion.
