### ISSUE TITLE
installation of BITE

### ISSUE THREAD

**Issue by Yyeserin** [marcomilanesi/BITE#8]
Hi there!

I have problems in installing/running the program in linux. I just unzipped scripts, and ran bash files with an input file that I got from stacks. 

Below is the script that fails followed by the progress of the run. Do you think that it is related to installation?  There are many R scripts. Are they to be used after running bash files? Or do I need to install them?

I hope that you can help me. 

Thanks!
Best,
Yeserin.

**bash BITE/inst/scripts/treemix_scripts/Treemix_bootstrap.sh populations.treemix.gz  0 4 2 NoOutgroup 3  /home/yeserin/snphylo/phylip-3.697/exe/consense out.0**
 
 
_mkdir: cannot create directory ‘bootstrap’: File exists
**** RUNNING TREEMIX ****
BITE/inst/scripts/treemix_scripts/Treemix_bootstrap.sh: line 55: parallel: command not found
**** RUNNING TREEMIX: DONE ****
gzip: bootstrap/out.0_treemix_bootrep_1.treeout.gz: No such file or directory
gzip: bootstrap/out.0_treemix_bootrep_2.treeout.gz: No such file or directory
gzip: bootstrap/out.0_treemix_bootrep_3.treeout.gz: No such file or directory
   ***** Boostrap procedure: DONE *****
   ***** Phylip - consensus tree construction: START *****
   ***** Phylip - consensus tree construction: DONE *****
**** RUNNING TREEMIX with Consensus tree ****
Warning: no counts at SNP 2 population 1
Warning: no counts at SNP 2 population 8
Warning: no counts at SNP 3 population 1......
.....
ERROR: Input Newick string with 1 populations. Input file has 14
**** RUNNING TREEMIX: DONE ****
TreeMix - Bootstrap Analysis --> DONE_

**Comment by capemaster** [comment]
Hi,
I'm not quite sure about your issue.
It seems that you tried to use the pre-cooked scripts.
Can you be more precise about what you are trying to achieve?

Stefano

**Comment by Yyeserin** [comment]
Hi again,

What is a pre-cooked script? If there are proper scripts available, could you please provide them? A link for the manual would be great. 

I am trying to run Treemix_bootstrap.sh script in BITE package to get the treemix results. I want to use the resulting files to find the best m, and then draw a tree with that m value. I progressed a bit more since my previous message. But still the runs fail. 

I'm using linux (Uppmax super computer infrastructure), and my input file is in treemix.gz format.  Uppmax already has Treemix v.1.12 installed. So I call that program. This is my code:

_module load TreeMix/1.12
module load gnuparallel

bash ./Step1_TreeMix.sh populations.snps.92ind.tmix.gz 4 1 noRoot 100 /home/yeserin/snphylo/phylip-3.697/exe/consense Step1_out/3spine 1 10 10_

The program now fails, and the slurm file has this information. I chopped the list of missing data part.

_"mkdir: cannot create directory â€˜bootstrapâ€™: File exists
**** RUNNING TREEMIX ****
Warning: no counts at SNP 2 population 1
Warning: no counts at SNP 2 population 8
Warning: no counts at SNP 16142 population 1
Warning: no counts at SNP 16142 population 8
**** RUNNING TREEMIX: DONE ****
TreeMix - Bootstrap Analysis --> DONE_

The screenout file has this warning:
_"ERROR in user tree: name FIN2 not found in first tree_"

The same code at least works with HapMap3_chr2_subsample_treemix_Input_treemix.frq.gz". 

I suspect that may be missing data creates this problem. Do I need to remove all the missing data before running the program? So far I keep a locus if it exists in 80% of the individuals. 

Best,
Yeserin.

**Comment by capemaster** [comment]
Hi 
I see that the script cannot create the "boostrap/" directory because it is already in the path.
try renaming your results or the directory and see if it works.
Also check for the correct naming of the populations. 

Best

**Comment by Yyeserin** [comment]
Hi there,

Neither the existing directory nor the population names were the problem. It was the amount of missing data. Probably some populations did not share some loci, then the trees didn't contain the all population pairs. Using less missing data has solved the problem so far. 

Thank you for your reply.

**Comment by capemaster** [comment]
Ok,
glad you found the solution.
I will close the issue.
